default_velocity_scaling_factor: 1.0       # Scales to 100% of max velocity
default_acceleration_scaling_factor: 1.0   # Scales to 100% of max acceleration

joint_limits:
  meca_axis_1:
    has_velocity_limits: true
    max_velocity: 2.61079
    has_acceleration_limits: true
    max_acceleration: 16.78365
  meca_axis_2:
    has_velocity_limits: true
    max_velocity: 2.61079
    has_acceleration_limits: true
    max_acceleration: 16.78365
  meca_axis_3:
    has_velocity_limits: true
    max_velocity: 2.61079
    has_acceleration_limits: true
    max_acceleration: 16.78365
  meca_axis_4:
    has_velocity_limits: true
    max_velocity: 4.06182
    has_acceleration_limits: true
    max_acceleration: 26.1117
  meca_axis_5:
    has_velocity_limits: true
    max_velocity: 4.06182
    has_acceleration_limits: true
    max_acceleration: 26.1117
  meca_axis_6:
    has_velocity_limits: true
    max_velocity: 5.80279
    has_acceleration_limits: true
    max_acceleration: 37.30365