controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    meca_velocity_controller:
      type: joint_trajectory_controller/JointTrajectoryController

meca_velocity_controller:
  ros__parameters:
    joints:
      - meca_axis_1
      - meca_axis_2
      - meca_axis_3
      - meca_axis_4
      - meca_axis_5
      - meca_axis_6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity